remote_theme: pages-themes/primer@v0.2.0
title: Almog Baku - LLM developer and strategist
description: >-
  Experienced LLM developer and strategist. Empowering organizations to harness 
  the power of Large Language Models through hands-on consulting, from concept 
  to production.

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

show_downloads: false